// <auto-generated />
using System;
using APIDemoStudent.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIDemoStudent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241221182223_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIDemoStudent.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photopath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            DateOfBirth = new DateTime(2003, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "leemisa@gmail.com",
                            FirstName = "Leemisa",
                            Gender = 0,
                            LastName = "Moleko",
                            Photopath = "Images/leemisa.png"
                        },
                        new
                        {
                            StudentId = 2,
                            DateOfBirth = new DateTime(2003, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "john@gmail.com",
                            FirstName = "John",
                            Gender = 0,
                            LastName = "Doe",
                            Photopath = "images/john.png"
                        },
                        new
                        {
                            StudentId = 3,
                            DateOfBirth = new DateTime(2004, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "jane@gmail.com",
                            FirstName = "Jane",
                            Gender = 1,
                            LastName = "Doe",
                            Photopath = "images/john.png"
                        },
                        new
                        {
                            StudentId = 4,
                            DateOfBirth = new DateTime(2005, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "jons@gmail.com",
                            FirstName = "Natalie",
                            Gender = 1,
                            LastName = "Jons",
                            Photopath = "images/john.png"
                        },
                        new
                        {
                            StudentId = 5,
                            DateOfBirth = new DateTime(2003, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "mike@gmail.com",
                            FirstName = "Mike",
                            Gender = 2,
                            LastName = "Rose",
                            Photopath = "images/john.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
